// <auto-generated />
using System;
using Automais.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Automais.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260103235916_router2")]
    partial class router2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Automais.Core.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChirpStackApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("chirp_stack_application_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_applications_tenant_id_name");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("Automais.Core.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<double?>("BatteryLevel")
                        .HasColumnType("double precision")
                        .HasColumnName("battery_level");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DevEui")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("dev_eui");

                    b.Property<string>("DeviceProfileId")
                        .HasColumnType("text")
                        .HasColumnName("device_profile_id");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<double?>("SignalStrength")
                        .HasColumnType("double precision")
                        .HasColumnName("signal_strength");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("VpnEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("vpn_enabled");

                    b.Property<string>("VpnIpAddress")
                        .HasColumnType("text")
                        .HasColumnName("vpn_ip_address");

                    b.Property<Guid?>("VpnNetworkId")
                        .HasColumnType("uuid")
                        .HasColumnName("vpn_network_id");

                    b.Property<string>("VpnPublicKey")
                        .HasColumnType("text")
                        .HasColumnName("vpn_public_key");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_devices_application_id");

                    b.HasIndex("VpnNetworkId")
                        .HasDatabaseName("ix_devices_vpn_network_id");

                    b.HasIndex("TenantId", "DevEui")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_tenant_id_dev_eui");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Automais.Core.Entities.Gateway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("GatewayEui")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("gateway_eui");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_gateways");

                    b.HasIndex("GatewayEui")
                        .IsUnique()
                        .HasDatabaseName("ix_gateways_gateway_eui");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_gateways_tenant_id");

                    b.ToTable("gateways", (string)null);
                });

            modelBuilder.Entity("Automais.Core.Entities.Router", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("firmware_version");

                    b.Property<string>("HardwareInfo")
                        .HasColumnType("text")
                        .HasColumnName("hardware_info");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("RouterOsApiPassword")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("router_os_api_password");

                    b.Property<string>("RouterOsApiUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("router_os_api_url");

                    b.Property<string>("RouterOsApiUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("router_os_api_username");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VpnNetworkId")
                        .HasColumnType("uuid")
                        .HasColumnName("vpn_network_id");

                    b.HasKey("Id")
                        .HasName("pk_routers");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_routers_serial_number")
                        .HasFilter("\"serial_number\" IS NOT NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_routers_tenant_id");

                    b.HasIndex("VpnNetworkId")
                        .HasDatabaseName("ix_routers_vpn_network_id");

                    b.ToTable("routers", (string)null);
                });

            modelBuilder.Entity("Automais.Core.Entities.RouterBackup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CommandCount")
                        .HasColumnType("integer")
                        .HasColumnName("command_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_automatic");

                    b.Property<Guid>("RouterId")
                        .HasColumnType("uuid")
                        .HasColumnName("router_id");

                    b.Property<string>("RouterModel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("router_model");

                    b.Property<string>("RouterOsVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("router_os_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_router_backups");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_router_backups_created_at");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_router_backups_created_by_user_id");

                    b.HasIndex("RouterId")
                        .HasDatabaseName("ix_router_backups_router_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_router_backups_tenant_id");

                    b.ToTable("router_backups", (string)null);
                });

            modelBuilder.Entity("Automais.Core.Entities.RouterConfigLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("AfterValue")
                        .HasColumnType("text")
                        .HasColumnName("after_value");

                    b.Property<string>("BeforeValue")
                        .HasColumnType("text")
                        .HasColumnName("before_value");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("ConfigPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("config_path");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<Guid?>("PortalUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("portal_user_id");

                    b.Property<Guid>("RouterId")
                        .HasColumnType("uuid")
                        .HasColumnName("router_id");

                    b.Property<string>("RouterOsUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("router_os_user");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_router_config_logs");

                    b.HasIndex("PortalUserId")
                        .HasDatabaseName("ix_router_config_logs_portal_user_id");

                    b.HasIndex("RouterId")
                        .HasDatabaseName("ix_router_config_logs_router_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_router_config_logs_tenant_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_router_config_logs_timestamp");

                    b.ToTable("router_config_logs", (string)null);
                });

            modelBuilder.Entity("Automais.Core.Entities.RouterWireGuardPeer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllowedIps")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("allowed_ips");

                    b.Property<long?>("BytesReceived")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_received");

                    b.Property<long?>("BytesSent")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_sent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("endpoint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastHandshake")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_handshake");

                    b.Property<int?>("ListenPort")
                        .HasColumnType("integer")
                        .HasColumnName("listen_port");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("private_key");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("public_key");

                    b.Property<Guid>("RouterId")
                        .HasColumnType("uuid")
                        .HasColumnName("router_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VpnNetworkId")
                        .HasColumnType("uuid")
                        .HasColumnName("vpn_network_id");

                    b.HasKey("Id")
                        .HasName("pk_router_wireguard_peers");

                    b.HasIndex("RouterId")
                        .HasDatabaseName("ix_router_wireguard_peers_router_id");

                    b.HasIndex("VpnNetworkId")
                        .HasDatabaseName("ix_router_wireguard_peers_vpn_network_id");

                    b.HasIndex("RouterId", "VpnNetworkId")
                        .IsUnique()
                        .HasDatabaseName("ix_router_wireguard_peers_router_id_vpn_network_id");

                    b.ToTable("router_wireguard_peers", (string)null);
                });

            modelBuilder.Entity("Automais.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChirpStackTenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chirp_stack_tenant_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Automais.Core.Entities.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VpnDeviceName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("vpn_device_name");

                    b.Property<bool>("VpnEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("vpn_enabled");

                    b.Property<string>("VpnIpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vpn_ip_address");

                    b.Property<string>("VpnPublicKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("vpn_public_key");

                    b.HasKey("Id")
                        .HasName("pk_tenant_users");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_users_tenant_id_email");

                    b.ToTable("tenant_users", (string)null);
                });

            modelBuilder.Entity("Automais.Core.Entities.VpnNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cidr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cidr");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DnsServers")
                        .HasColumnType("text")
                        .HasColumnName("dns_servers");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_vpn_networks");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_vpn_networks_tenant_id_slug");

                    b.ToTable("vpn_networks", (string)null);
                });

            modelBuilder.Entity("Automais.Core.Entities.VpnNetworkMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assigned_ip");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TenantUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_user_id");

                    b.Property<Guid>("VpnNetworkId")
                        .HasColumnType("uuid")
                        .HasColumnName("vpn_network_id");

                    b.HasKey("Id")
                        .HasName("pk_vpn_network_memberships");

                    b.HasIndex("TenantUserId")
                        .HasDatabaseName("ix_vpn_network_memberships_tenant_user_id");

                    b.HasIndex("VpnNetworkId", "TenantUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_vpn_network_memberships_vpn_network_id_tenant_user_id");

                    b.ToTable("vpn_network_memberships", (string)null);
                });

            modelBuilder.Entity("Automais.Core.Entities.Application", b =>
                {
                    b.HasOne("Automais.Core.Entities.Tenant", "Tenant")
                        .WithMany("Applications")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applications_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Automais.Core.Entities.Device", b =>
                {
                    b.HasOne("Automais.Core.Entities.Application", "Application")
                        .WithMany("Devices")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_applications_application_id");

                    b.HasOne("Automais.Core.Entities.Tenant", "Tenant")
                        .WithMany("Devices")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_tenants_tenant_id");

                    b.HasOne("Automais.Core.Entities.VpnNetwork", "VpnNetwork")
                        .WithMany("Devices")
                        .HasForeignKey("VpnNetworkId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_devices_vpn_networks_vpn_network_id");

                    b.Navigation("Application");

                    b.Navigation("Tenant");

                    b.Navigation("VpnNetwork");
                });

            modelBuilder.Entity("Automais.Core.Entities.Gateway", b =>
                {
                    b.HasOne("Automais.Core.Entities.Tenant", "Tenant")
                        .WithMany("Gateways")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gateways_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Automais.Core.Entities.Router", b =>
                {
                    b.HasOne("Automais.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_routers_tenants_tenant_id");

                    b.HasOne("Automais.Core.Entities.VpnNetwork", "VpnNetwork")
                        .WithMany()
                        .HasForeignKey("VpnNetworkId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_routers_vpn_networks_vpn_network_id");

                    b.Navigation("Tenant");

                    b.Navigation("VpnNetwork");
                });

            modelBuilder.Entity("Automais.Core.Entities.RouterBackup", b =>
                {
                    b.HasOne("Automais.Core.Entities.TenantUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_router_backups_tenant_users_created_by_user_id");

                    b.HasOne("Automais.Core.Entities.Router", "Router")
                        .WithMany("Backups")
                        .HasForeignKey("RouterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_router_backups_routers_router_id");

                    b.HasOne("Automais.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_router_backups_tenants_tenant_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Router");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Automais.Core.Entities.RouterConfigLog", b =>
                {
                    b.HasOne("Automais.Core.Entities.TenantUser", "PortalUser")
                        .WithMany()
                        .HasForeignKey("PortalUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_router_config_logs_tenant_users_portal_user_id");

                    b.HasOne("Automais.Core.Entities.Router", "Router")
                        .WithMany("ConfigLogs")
                        .HasForeignKey("RouterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_router_config_logs_routers_router_id");

                    b.HasOne("Automais.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_router_config_logs_tenants_tenant_id");

                    b.Navigation("PortalUser");

                    b.Navigation("Router");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Automais.Core.Entities.RouterWireGuardPeer", b =>
                {
                    b.HasOne("Automais.Core.Entities.Router", "Router")
                        .WithMany("WireGuardPeers")
                        .HasForeignKey("RouterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_router_wireguard_peers_routers_router_id");

                    b.HasOne("Automais.Core.Entities.VpnNetwork", "VpnNetwork")
                        .WithMany()
                        .HasForeignKey("VpnNetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_router_wireguard_peers_vpn_networks_vpn_network_id");

                    b.Navigation("Router");

                    b.Navigation("VpnNetwork");
                });

            modelBuilder.Entity("Automais.Core.Entities.TenantUser", b =>
                {
                    b.HasOne("Automais.Core.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Automais.Core.Entities.VpnNetwork", b =>
                {
                    b.HasOne("Automais.Core.Entities.Tenant", "Tenant")
                        .WithMany("VpnNetworks")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vpn_networks_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Automais.Core.Entities.VpnNetworkMembership", b =>
                {
                    b.HasOne("Automais.Core.Entities.TenantUser", "TenantUser")
                        .WithMany("VpnMemberships")
                        .HasForeignKey("TenantUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vpn_network_memberships_tenant_users_tenant_user_id");

                    b.HasOne("Automais.Core.Entities.VpnNetwork", "VpnNetwork")
                        .WithMany("Memberships")
                        .HasForeignKey("VpnNetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vpn_network_memberships_vpn_networks_vpn_network_id");

                    b.Navigation("TenantUser");

                    b.Navigation("VpnNetwork");
                });

            modelBuilder.Entity("Automais.Core.Entities.Application", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Automais.Core.Entities.Router", b =>
                {
                    b.Navigation("Backups");

                    b.Navigation("ConfigLogs");

                    b.Navigation("WireGuardPeers");
                });

            modelBuilder.Entity("Automais.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Devices");

                    b.Navigation("Gateways");

                    b.Navigation("Users");

                    b.Navigation("VpnNetworks");
                });

            modelBuilder.Entity("Automais.Core.Entities.TenantUser", b =>
                {
                    b.Navigation("VpnMemberships");
                });

            modelBuilder.Entity("Automais.Core.Entities.VpnNetwork", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
